# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Od8Ss3hz6mYokZtuVfAsJzgtdMno-S3
"""

import geopandas as gpd

gdf = gpd.read_file('lka_admbnda_adm2_slsd_20220816.shp')
gdf

import matplotlib.pyplot as plt

fig, ax = plt.subplots(1, 1, figsize=(10, 10))
gdf.plot(ax=ax)
plt.show()

# Calculate the area of the Western province
western_province_area = provinces.loc['Western', 'Shape_Area']

# Display the area
print(f"The area of the Western province is: {western_province_area} km")
print(gdf.crs)

provinces_projected = provinces.to_crs(epsg=32644)

# Calculate the area of the Western province in square meters
western_province_area_sq_m = provinces_projected.loc['Western', 'geometry'].area

# Convert the area from square meters to square kilometers
western_province_area_sq_km = western_province_area_sq_m / 1_000_000

# Display the area in square kilometers
print(f"The area of the Western province is: {western_province_area_sq_km:.2f} square km")

import matplotlib.pyplot as plt

fig, ax = plt.subplots(1, 1, figsize=(10, 10))

# Group by 'ADM1_EN' (province) and plot
provinces = gdf.dissolve(by='ADM1_EN')
provinces.plot(ax=ax)

# Add province names as labels
for idx, row in provinces.iterrows():
    ax.annotate(text=row.name, xy=row.geometry.centroid.coords[0],
                 horizontalalignment='center')

plt.show()

